### ISSUE TITLE
order of arguments in object methods

### ISSUE THREAD

**Issue by cboettig** [cloudyr/aws.s3#28]
Okay, this seems a bit nit-picky, but there's some inconsistency in how the various `object` methods order there arguments; particularly, whether they take a file name first or a bucket name first.  I'd argue that they should always take the file name first, as the bucket name is more of a parameter, and this makes it more consise to `lapply` over a list of files or what not.  

But maybe it's not worth breaking the package API just to make that change. (and maybe the current format is more consistent with other wrappers like boto?)  Anyway, just thought I'd mention it.

**Comment by leeper** [comment]
I actually had the same thought at some point. I'm not worried about breaking the API. I think we should aim for 0.2.0 as a stable release (I created a milestone for that) but we can do whatever we want up until then.

I also noted that I initially setup inconsistent case in function names. Some use snake case (e.g., `get_cors`) and some are just words put together (e.g., `getobject`). I thought it would be good to have a style guide for the whole cloudyr suite of packages. It would make sense to decide that here so I/we can follow a common convention throughout.

**Comment by cboettig** [comment]
:+1:

**Comment by almartin82** [comment]
agreed on consistent case!

**Comment by leeper** [comment]
I'm pushing an update right now that uses `object` as first argument consistently, which should simplify `lapply` operations. I've also updated `getbucket()` to store the bucket name in each object, so that you these functions can look there for the bucketname instead of having to explicitly supply a bucket.

On function naming, we should probably go with snake case as that is the style throughout cloudyr. I'm going to push an update with that in mind, leaving in undocumented non-snake versions as a legacy.
