### ISSUE TITLE
Error in sprintf when I call s3.wirte_using()

### ISSUE THREAD

**Issue by Jiang-Li** [cloudyr/aws.s3#329]
I saw `Error in sprintf("File size is %d. Consider setting 'multipart = TRUE'.",  : 
  invalid format '%d'; use format %f, %e, %g or %a for numeric objects`

When I tried to lead a large data frame. The smaller data frame is OK.

**Comment by JanLauGe** [comment]
Upvote! This is due some idiosyncrasies of `numeric` in R and `sprintf()`. The problem is caused by [this line](https://github.com/cloudyr/aws.s3/blob/46aa3db34b89946205e6f27ce6f745cea4bf4571/R/put_object.R#L184) and [here](https://stackoverflow.com/questions/27107405/sprintf-invalid-format-d) is a related post explaining the root cause of the problem. Suggest to either convert `headers[["Content-Length"]]` to numeric first or to avoid using `sprintf()`.
