### ISSUE TITLE
More useful out-of-region errors

### ISSUE THREAD

**Issue by leeper** [cloudyr/aws.s3#46]
Apparently errors for out-of-region bucket requests currently look a little cryptic (see #45). It would be good to clearly communicate what is going on.

**Comment by leeper** [comment]
May be able to get around this by having a call to `get_location()` to confirm the bucket region (note a blank string means `us-east-1`) before attempting any call.

http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlocation.html

**Comment by elinw** [comment]
This same message is returned whenever the data set is not found, even if it is not due to region. For example if you make a typing mistake. I don't know if it is possible to return a more meaningful message.

**Comment by leeper** [comment]
Unfortunately, there's no way to distinguish a typo from a region error, as far as I know. If you find that this is possible somewhere (e.g., in Python's boto library), let me know.

**Comment by elinw** [comment]
I think the issue is actually coming from r around line 2383  here http://docs.rexamine.com/R-devel/saveload_8c_source.html   the problem is, I think, that the aws_error is not being caught and is just getting sent along as though it was an invalid filename, triggering this message.  I think if you caught the aws_error and  stop() and either return the actual AWS error text or a message like "something is wrong with your request" that would be more user friendly.  I haven't tested but just looking at the way nothing is happening when there is an error.  I'm sensitive on this because I have a lot of undergraduates pulling data from my bucket.

**Comment by leeper** [comment]
You've lost me. Can you give some context for what you're saying and maybe show me the error you're encountering (in a new issue)?

**Comment by elinw** [comment]
Sure thing
https://github.com/cloudyr/aws.s3/issues/105

**Comment by leeper** [comment]
Thanks.
