### ISSUE TITLE
Needs POST methods implemented

### ISSUE THREAD

**Issue by cboettig** [cloudyr/aws.s3#5]
Got bogged down my the region thing so didn't have a chance to play with this yet, but on the to-do list.  might involve more package API breakage.

**Comment by cboettig** [comment]
@leeper @almartin82 I took a stab at this without success, cannot seem to get AWS to be happy with the signatures for my POST method.  Perhaps related to my construction of the JSON policy document; not clear if `aws.signatures` covers this case.

Here's what I'm trying: https://github.com/cloudyr/aws.s3/blob/148886f37cea26e6341f21f3a74979f6e8425d6a/inst/experiments/post-experiment.md

Perhaps you can spot what I'm doing wrong.  Any help would be appreciated! thanks,

**Comment by leeper** [comment]
I'd say start with trying to figure out the [PUT object method](
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html). They
are probably going to be easier than POST, based on what you're doing here.
I think we just need to figure out how to pass an object through the
signature function.

For example, the current function `putobject` will be a successful API
request but it won't actually put anything in the bucket because it's not
yet setup to actually pass the body through to `s3HTTP` (and `s3HTTP` was
using a hard-coded value of "" for this; which I've changed).

I'm not sure that the signature function is setup to correctly process a
value for `request_body` other than `""`, so we may need to make changes
there once we get this figured out.

Also, in your example you should have `key =
Sys.getenv("AWS_ACCESS_KEY_ID")` (note the `_ID`).

**Comment by cboettig** [comment]
Looks like my bucket policy had allowed GET, PUT, and DELETE but not POST methods.

**Comment by almartin82** [comment]
oh, interesting -- what kind of a response did that return (valid request
but disallowed by policy)?

**Comment by cboettig** [comment]
looks like I still have signature issues as well, so I'm still get invalid signature either way.  oops.

**Comment by leeper** [comment]
I don't think we actually need POST for anything do we, given that we have `put_object()`? There's a dummy function for it (non-exported) in `put_object.R` so we could easily make this work and release it but unless there's an obvious use case I'm closing.
