### ISSUE TITLE
Creating a new folder

### ISSUE THREAD

**Issue by tchakravarty** [cloudyr/aws.s3#57]
@leeper 

Thanks for the excellent package. Just wondering if there is a method to create a new folder in a 
bucket using `aws.s3`?

Thanks.

**Comment by leeper** [comment]
Buckets are flat structures, so there are no folders per se. If you go into the S3 web interface and see folders, you're actually just seeing object "prefixes" treated as pseudo-folders. So, let's say you create an object called "foo.txt" that is stored in "top" of this fake directory index. "bar/foo2.txt" is also stored at the top level (because there is only one level in a bucket) but the web interface displays it as "foo2.txt" in a "/bar" directory.

So, if you want to see directories in the web interface, just name the objects with a directory-like prefix.
