### ISSUE TITLE
Dependency on xml2 > 1.0.0

### ISSUE THREAD

**Issue by msuchard** [cloudyr/aws.s3#61]
xml2 1.0.0 was just posted to CRAN in July and > 1.0.0 is only available via github_install.  Might it be possible to revert to >= 1.0.0 dependence?

**Comment by leeper** [comment]
Unfortunately xml2 v1.0.0 broke everything in this package, so you really need the Github patched version, which fixes the problems.

**Comment by cboettig** [comment]
Until the next CRAN release of xml2, perhaps it would be good to add `Remotes: hadley/xml2` to the DESCRIPTION so that `devtools::install_github` gets the right version? 

(or maybe you've already handled this with your drat repo, haven't tested).

**Comment by leeper** [comment]
The simple solution, I think, is to just add xml2 to the cloudyr's drat. I've done this. I've also added a windows 3.3 binary to the drat, so it should be installable on Windows using `install.packages()`, as well (this is unfortunately not at all straightforward using any flavor of `install_github()`).

I've updated the README with install instructions that reflect these changes.

**Comment by cboettig** [comment]
Adding the remotes line to the Description is all you need to make install_github work. It's not well documented but you can see it in use on the dplyr repo and others.

**Comment by PeterAttardo** [comment]
The version of xml2 present in cloudyr's drat will not install on OSX or Linux. The error given:

`* installing *source* package ‘xml2’ ...
sh: ./configure: /bin/bash^M: bad interpreter: No such file or directory
ERROR: configuration failed for package ‘xml2’
* removing ‘/usr/local/lib/R/3.2/site-library/xml2’
ERROR: dependency ‘xml2’ is not available for package ‘aws.s3’
* removing ‘/usr/local/lib/R/3.2/site-library/aws.s3’`

I cracked open the tarball at http://cloudyr.github.io/drat/src/contrib/xml2_1.0.0.9000.tar.gz and it appears that the configure file has a number of Windows style line end characters, causing the shebang line to point to /bin/bash^M instead of /bin/bash.

**Comment by cboettig** [comment]
@PeterAttardo can you try:

```r
devtools::install_github("cloudyr/aws.s3@cboettig")
```

and see if that works for you? (working here on Linux)

**Comment by PeterAttardo** [comment]
@cboettig That worked. I must say, 9 minutes from comment to PR might be a record.
