### ISSUE TITLE
How to read JSON file?

### ISSUE THREAD

**Issue by tiantian31** [cloudyr/aws.s3#68]
JSON file got read into a raw vector using get_object successfully, but how do I convert it back to JSON file from raw vector?

**Comment by tiantian31** [comment]
Thanks for your prompt reply! After further inspection, due to the original format of the JSON file, there were escape \ and \n in the raw vector which was preventing the conversion in R. After formatting the raw vector in the right manner, the conversion was successful!

**Comment by leeper** [comment]
Great!

**Comment by rachitkinger** [comment]
@tiantian31 nearly 2 years later. I am facing the same challenge. how did you format the raw vector "in the right manner", if you have any recollection that will be helpful.

**Comment by amanda-hand** [comment]
@rachitkinger  I have the same question.  Any response, @tiantian31 ?

**Comment by rachitkinger** [comment]
@amanda-hand Sorry, I tried to look for which project I was solving this for but can't find it. Sorry about that. But if I recollect correctly, the problem was that my json had `\n` after every line and I solved it by substituting `\n` with blank values on the raw string before parsing it to json, quite possibly by using gsub(). If you can share an example of your rawdata here or on stackoverflow or on twitter I will try to give it a go. I go by the same username.
